import type { Metadata } from "next";
import { Google_Sans_Code } from "next/font/google";
import "../globals.css";
import Navbar from "./components/navigation/Navbar";
import { Toaster } from "sonner";
import Footer from "@/components/ui/Footer";

const sansCode = Google_Sans_Code({
	variable: "--font-sans-code",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${sansCode.variable} font-sans-code antialiased`}>
				<Navbar />
				{children}
				<Toaster />
				<Footer />
			</body>
		</html>
	);
}
